version: '3.9'
services:
  redirect-web:
    build: .
    image: shortlink
    container_name: shortlink
    restart: always
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - NODE_ENV=production
    ports:
      - "5000:5000"
    networks:
      - redirect-project
    
  mongo:
    image: mongo
    container_name: mongo-db
    restart: always
    volumes:
      - mongo-data:/data/db
    networks:
      - redirect-project

volumes:
  mongo-data:

networks:
  redirect-project: